@startuml
actor User
participant "Scene" as Scene
participant BoardPlayView
participant BoardPlayViewModel
participant BoardPlay
participant MoveExecutor
participant MoveCommandeDirection
participant MapPlay
participant Box

User -> BoardPlayView: Instantiate
activate BoardPlayView
BoardPlayView -> Scene: Set Key Pressed Event
activate Scene
Scene -> BoardPlayViewModel: Check if game is not won
activate BoardPlayViewModel
BoardPlayViewModel -> BoardPlay: Perform move up
activate BoardPlay
BoardPlay -> MoveExecutor: Execute move up
activate MoveExecutor
MoveExecutor -> MoveCommandeDirection: Create moveCommandeDirection for move up
activate MoveCommandeDirection
MoveCommandeDirection -> MapPlay: Call moveUp()
activate MapPlay
MapPlay -> MapPlay: Perform move up
MapPlay -> MoveCommandeDirection: Undo move
deactivate MapPlay
deactivate MoveCommandeDirection
MoveExecutor --> BoardPlay: Continue
deactivate MoveExecutor
BoardPlay --> BoardPlayViewModel: Move up result
deactivate BoardPlay
BoardPlayViewModel -> BoardPlay: Perform move back
activate BoardPlay
BoardPlay -> MoveExecutor: Execute move back
activate MoveExecutor
MoveExecutor -> MoveCommandeDirection: Undo move()
deactivate MoveExecutor
BoardPlay --> BoardPlayViewModel: Move back result
deactivate BoardPlay
BoardPlayViewModel -> BoardPlay: Perform move front
activate BoardPlay
BoardPlay -> MoveExecutor: Execute move front
activate MoveExecutor
MoveExecutor -> MoveCommandeDirection: DoMove
activate MoveCommandeDirection
MoveCommandeDirection -> MapPlay: Call moveUp()
activate MapPlay
MapPlay -> MapPlay: Perform move up()
deactivate MapPlay
deactivate MoveCommandeDirection
MoveExecutor --> BoardPlay: Continue
deactivate MoveExecutor
BoardPlay --> BoardPlayViewModel: Move front result
deactivate BoardPlay
BoardPlayViewModel --> Scene: Continue
deactivate BoardPlayViewModel
Scene --> BoardPlayView: Continue
deactivate Scene
@enduml
